language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nikhil08652/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true nikhil08652/docker-react npm run test

 deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-281984316183"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
