language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nikhil08652/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true nikhil08652/docker-react npm run test